// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Non authentifi\xE9 : reconnecte le compte ForSure." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my ForSure profile",
  description: "Read the signed-in user's ForSure profile (name, bio, city, mood, creator status).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("id, user_id, name, bio, city, website_url, mood_emoji, mood_text, is_creator, creator_tier, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Aucun profil trouv\xE9 pour ce compte.");
    return jsonResult({ profile: data });
  }
});

// src/lib/mcp/tools/update-my-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var update_my_profile_default = defineTool2({
  name: "update_my_profile",
  title: "Update my ForSure profile",
  description: "Update editable fields of the signed-in user's ForSure profile. Only provided fields change.",
  inputSchema: {
    name: z.string().trim().min(1).max(80).nullable().optional().describe("Display name."),
    bio: z.string().trim().max(500).nullable().optional().describe("Short biography."),
    city: z.string().trim().max(120).nullable().optional().describe("City shown on the profile."),
    website_url: z.string().trim().url().max(300).nullable().optional().describe("Public website URL."),
    mood_emoji: z.string().trim().max(8).nullable().optional().describe("Mood emoji."),
    mood_text: z.string().trim().max(120).nullable().optional().describe("Short mood text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const patch = {};
    for (const key of ["name", "bio", "city", "website_url", "mood_emoji", "mood_text"]) {
      if (input[key] !== void 0) patch[key] = input[key];
    }
    if (Object.keys(patch).length === 0) return errorResult("Aucun champ \xE0 mettre \xE0 jour.");
    if ("mood_emoji" in patch || "mood_text" in patch) patch.mood_updated_at = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabaseForUser(ctx).from("profiles").update(patch).eq("user_id", ctx.getUserId()).select("id, name, bio, city, website_url, mood_emoji, mood_text").maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Profil introuvable ou mise \xE0 jour refus\xE9e.");
    return jsonResult({ profile: data });
  }
});

// src/lib/mcp/tools/list-my-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_posts_default = defineTool3({
  name: "list_my_posts",
  title: "List my ForSure posts",
  description: "List the signed-in user's most recent ForSure posts with their like and comment counts.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many posts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("posts").select("id, body, image_url, created_at, publish_at, likes_count, comments_count").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, posts: data ?? [] });
  }
});

// src/lib/mcp/tools/create-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_post_default = defineTool4({
  name: "create_post",
  title: "Publish a ForSure post",
  description: "Publish a text post (optionally with an image URL) on the signed-in user's ForSure feed. Can also be scheduled for later.",
  inputSchema: {
    body: z3.string().trim().min(1).max(5e3).describe("The post text."),
    image_url: z3.string().trim().url().max(1e3).nullable().optional().describe("Optional image URL to attach."),
    publish_at: z3.string().trim().nullable().optional().describe("Optional ISO 8601 datetime to schedule the post instead of publishing immediately.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ body, image_url, publish_at }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let scheduledAt = null;
    if (publish_at) {
      const parsed = new Date(publish_at);
      if (Number.isNaN(parsed.getTime())) return errorResult("publish_at n'est pas une date ISO valide.");
      scheduledAt = parsed.toISOString();
    }
    const { data, error } = await supabaseForUser(ctx).from("posts").insert({
      user_id: ctx.getUserId(),
      body,
      image_url: image_url ?? null,
      ...scheduledAt ? { publish_at: scheduledAt } : {}
    }).select("id, body, image_url, created_at, publish_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ post: data, scheduled: Boolean(scheduledAt) });
  }
});

// src/lib/mcp/tools/list-notifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_notifications_default = defineTool5({
  name: "list_notifications",
  title: "List my ForSure notifications",
  description: "List the signed-in user's recent ForSure notifications, optionally only the unread ones.",
  inputSchema: {
    unread_only: z4.boolean().optional().describe("Return only unread notifications (default false)."),
    limit: z4.number().int().min(1).max(50).optional().describe("How many notifications to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("notifications").select("id, type, actor_id, post_id, read_at, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only) query = query.is("read_at", null);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, notifications: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "vkpmoqfzrihcijjochks";
var mcp_default = defineMcp({
  name: "forsure-mcp",
  title: "ForSure",
  version: "0.1.0",
  instructions: "Outils du r\xE9seau social ForSure pour l'utilisateur connect\xE9 : lire et mettre \xE0 jour son profil, lister ses publications, publier (ou programmer) un post et consulter ses notifications. Toutes les actions s'ex\xE9cutent au nom de l'utilisateur authentifi\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, update_my_profile_default, list_my_posts_default, create_post_default, list_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
