// This file is automatically generated. Keep local auth hardening minimal.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

let last401At = 0;

function readStoredAccessToken(storage: Storage): string | null {
  try {
    for (let i = 0; i < storage.length; i++) {
      const key = storage.key(i);
      if (!key || (!key.startsWith('sb-') && !key.startsWith('supabase.auth.'))) continue;
      const raw = storage.getItem(key);
      if (!raw) continue;
      try {
        const parsed = JSON.parse(raw);
        const token =
          parsed?.access_token ??
          parsed?.currentSession?.access_token ??
          parsed?.session?.access_token;
        if (typeof token === 'string' && token.length > 0) return token;
      } catch {}
    }
  } catch {}
  return null;
}

function currentStoredAccessToken(): string | null {
  if (typeof window === 'undefined') return null;
  return readStoredAccessToken(window.localStorage) ?? readStoredAccessToken(window.sessionStorage);
}

function requestBearerToken(input: Parameters<typeof fetch>[0], init?: Parameters<typeof fetch>[1]): string | null {
  try {
    const headers = new Headers(init?.headers ?? (
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined
    ));
    const auth = headers.get('authorization');
    const match = auth?.match(/^Bearer\s+(.+)$/i);
    return match?.[1] ?? null;
  } catch {
    return null;
  }
}

async function jwt401Reason(response: Response): Promise<'expired' | 'invalid' | 'malformed' | null> {
  try {
    const text = await response.clone().text();
    const lower = text.toLowerCase();
    if (!lower.includes('jwt')) return null;
    if (lower.includes('malformed')) return 'malformed';
    if (lower.includes('invalid')) return 'invalid';
    if (lower.includes('expired')) return 'expired';
    return null;
  } catch {
    return null;
  }
}

async function shouldClearAuthFor401(
  input: Parameters<typeof fetch>[0],
  init: Parameters<typeof fetch>[1] | undefined,
  response: Response,
): Promise<boolean> {
  const bearer = requestBearerToken(input, init);
  const stored = currentStoredAccessToken();
  if (!bearer || !stored || bearer !== stored) return false;
  const reason = await jwt401Reason(response);
  // Supabase can briefly send an expired access token while its refresh flow is
  // racing on mobile/PWA resumes. Let the auth client refresh instead of
  // deleting the whole session. Invalid/malformed JWTs are still purged.
  return reason === 'invalid' || reason === 'malformed';
}

function clearStaleSupabaseAuthSession(reason: string) {
  if (typeof window === 'undefined') return;
  try {
    const purge = (storage: Storage) => {
      const keys: string[] = [];
      for (let i = 0; i < storage.length; i++) {
        const k = storage.key(i);
        if (k && (k.startsWith('sb-') || k.startsWith('supabase.auth.'))) keys.push(k);
      }
      keys.forEach((k) => storage.removeItem(k));
    };
    purge(window.localStorage);
    purge(window.sessionStorage);
    window.dispatchEvent(new CustomEvent('forsure:auth-session-invalid', {
      detail: { reason },
    }));
  } catch {}
}

const guardedFetch: typeof fetch = async (input, init) => {
  const response = await fetch(input as RequestInfo | URL, init);
  try {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
    const isSupabaseRest = typeof url === 'string' && url.includes('/rest/v1/');
    if (response.status === 401 && isSupabaseRest) {
      const now = Date.now();
      if (now - last401At > 5_000 && await shouldClearAuthFor401(input, init, response)) {
        last401At = now;
        console.warn('[Supabase] REST 401 — invalid JWT session cleared, reconnect required');
        clearStaleSupabaseAuthSession('supabase-rest-401-invalid-jwt');
      }
    }
  } catch {}
  return response;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: guardedFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});
