// This file is automatically generated. Keep local auth hardening minimal.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { xhrFetch } from '@/lib/xhrFetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const capturedFetch: typeof fetch = globalThis.fetch.bind(globalThis);

let last401At = 0;
let confirmedAuthFailureCount = 0;
let authRecoveryInFlight: Promise<void> | null = null;
let supabaseClientRef: SupabaseClient<Database> | null = null;

function getRequestUrl(input: RequestInfo | URL): string {
  if (typeof input === 'string') return input;
  if (input instanceof URL) return input.toString();
  return input.url;
}

function clearStaleSupabaseAuthSession(reason = 'supabase-rest-401') {
  if (typeof window === 'undefined') return;
  try {
    const purge = (storage: Storage) => {
      const keys: string[] = [];
      for (let i = 0; i < storage.length; i++) {
        const k = storage.key(i);
        if (k && (k.startsWith('sb-') || k.startsWith('supabase.auth.'))) keys.push(k);
      }
      keys.forEach((k) => storage.removeItem(k));
    };
    purge(window.localStorage);
    purge(window.sessionStorage);
    window.dispatchEvent(new CustomEvent('forsure:auth-session-invalid', {
      detail: { reason },
    }));
  } catch {
    // Browser storage can be blocked or unavailable.
  }
}

function recoverSupabaseAuthAfter401(): void {
  if (typeof window === 'undefined') return;
  if (authRecoveryInFlight) return;

  authRecoveryInFlight = (async () => {
    try {
      const client = supabaseClientRef;
      if (!client?.auth) return;

      const { data: current } = await client.auth.getSession();
      if (current?.session) {
        const { data: refreshed, error } = await client.auth.refreshSession();
        if (!error && refreshed?.session) {
          confirmedAuthFailureCount = 0;
          console.warn('[Supabase] REST 401 - session refreshed; keeping auth state');
          window.dispatchEvent(new CustomEvent('forsure:auth-session-refreshed', {
            detail: { reason: 'supabase-rest-401' },
          }));
          return;
        }
        console.warn('[Supabase] REST 401 - refresh failed once; keeping auth pending retry', error?.message ?? error);
      } else {
        console.warn('[Supabase] REST 401 - no local session found during recovery');
      }

      confirmedAuthFailureCount += 1;
      if (confirmedAuthFailureCount >= 2) {
        console.warn('[Supabase] REST 401 - confirmed stale auth twice; clearing local session');
        clearStaleSupabaseAuthSession('supabase-rest-401-confirmed');
      }
    } catch (error) {
      confirmedAuthFailureCount += 1;
      console.warn('[Supabase] REST 401 - auth recovery threw; keeping session unless repeated', error);
      if (confirmedAuthFailureCount >= 2) {
        clearStaleSupabaseAuthSession('supabase-rest-401-recovery-failed');
      }
    } finally {
      authRecoveryInFlight = null;
    }
  })();
}

const guardedFetch: typeof fetch = async (input, init) => {
  const url = getRequestUrl(input);
  let response: Response;

  try {
    // Always prefer the browser's captured Fetch implementation. Supabase Auth
    // is designed and tested around Fetch; forcing every auth call through XHR
    // introduced a client-side 20-second timeout on otherwise healthy requests.
    response = await capturedFetch(input as RequestInfo | URL, init);
  } catch (error) {
    // Keep XHR only as a compatibility fallback for browsers/extensions that
    // break Fetch before the application starts. It is never the primary path.
    console.warn('[Supabase] fetch failed; retrying once with XHR transport', {
      url,
      error,
    });
    response = await xhrFetch(input, init);
  }

  try {
    const isSupabaseRest = url.includes('/rest/v1/');
    if (isSupabaseRest && response.ok) {
      confirmedAuthFailureCount = 0;
    }
    if (response.status === 401 && isSupabaseRest) {
      const now = Date.now();
      if (now - last401At > 5_000) {
        last401At = now;
        recoverSupabaseAuthAfter401();
      }
    }
  } catch {
    // Response inspection is best-effort and must not break the request.
  }
  return response;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: guardedFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});

supabaseClientRef = supabase;
