// This file is automatically generated. Keep local auth hardening minimal.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { xhrFetch } from '@/lib/xhrFetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const capturedFetch: typeof fetch = globalThis.fetch.bind(globalThis);

let last401At = 0;
let confirmedAuthFailureCount = 0;
let authRecoveryInFlight: Promise<void> | null = null;
let supabaseClientRef: SupabaseClient<Database> | null = null;

function getRequestUrl(input: RequestInfo | URL): string {
  if (typeof input === 'string') return input;
  if (input instanceof URL) return input.toString();
  return input.url;
}

function definitiveRefreshFailure(error: unknown): boolean {
  if (!error) return false;
  const value = error as { code?: unknown; message?: unknown; status?: unknown };
  const code = typeof value.code === 'string' ? value.code.toLowerCase() : '';
  const message = typeof value.message === 'string' ? value.message.toLowerCase() : '';
  const status = typeof value.status === 'number' ? value.status : 0;

  return code === 'refresh_token_not_found'
    || code === 'bad_jwt'
    || message.includes('invalid refresh token')
    || message.includes('refresh token not found')
    || message.includes('jwt expired')
    || message.includes('invalid jwt')
    || (status === 401 && message.includes('refresh'));
}

function clearStaleSupabaseAuthSession(reason = 'supabase-rest-401') {
  if (typeof window === 'undefined') return;
  try {
    const purge = (storage: Storage) => {
      const keys: string[] = [];
      for (let i = 0; i < storage.length; i++) {
        const k = storage.key(i);
        if (k && (k.startsWith('sb-') || k.startsWith('supabase.auth.'))) keys.push(k);
      }
      keys.forEach((k) => storage.removeItem(k));
    };
    purge(window.localStorage);
    purge(window.sessionStorage);
    window.dispatchEvent(new CustomEvent('forsure:auth-session-invalid', {
      detail: { reason },
    }));
  } catch {
    // Browser storage can be blocked or unavailable.
  }
}

function recoverSupabaseAuthAfter401(): void {
  if (typeof window === 'undefined') return;
  if (authRecoveryInFlight) return;

  authRecoveryInFlight = (async () => {
    try {
      const client = supabaseClientRef;
      if (!client?.auth) return;

      const { data: current, error: sessionError } = await client.auth.getSession();

      // A REST 401 before login is not evidence of a stale session. The previous
      // implementation counted these anonymous requests and deleted auth storage
      // after two occurrences, racing with signIn and PIN persistence.
      if (!current?.session) {
        confirmedAuthFailureCount = 0;
        console.warn('[Supabase] REST 401 - no local session; leaving auth storage untouched', {
          error: sessionError?.message ?? null,
        });
        return;
      }

      const { data: refreshed, error } = await client.auth.refreshSession();
      if (!error && refreshed?.session) {
        confirmedAuthFailureCount = 0;
        console.warn('[Supabase] REST 401 - session refreshed; keeping auth state');
        window.dispatchEvent(new CustomEvent('forsure:auth-session-refreshed', {
          detail: { reason: 'supabase-rest-401' },
        }));
        return;
      }

      if (!definitiveRefreshFailure(error)) {
        confirmedAuthFailureCount = 0;
        console.warn('[Supabase] REST 401 - refresh failed transiently; auth storage preserved', {
          error: error?.message ?? error,
        });
        return;
      }

      confirmedAuthFailureCount += 1;
      console.warn('[Supabase] REST 401 - definitive refresh failure', {
        attempt: confirmedAuthFailureCount,
        error: error?.message ?? error,
      });

      if (confirmedAuthFailureCount >= 2) {
        clearStaleSupabaseAuthSession('supabase-rest-401-confirmed-invalid-refresh');
      }
    } catch (error) {
      // Network/extension failures must never erase an otherwise usable session.
      confirmedAuthFailureCount = 0;
      console.warn('[Supabase] REST 401 - recovery check failed; auth storage preserved', error);
    } finally {
      authRecoveryInFlight = null;
    }
  })();
}

const guardedFetch: typeof fetch = async (input, init) => {
  const url = getRequestUrl(input);
  let response: Response;

  try {
    // Always prefer the browser's captured Fetch implementation. Supabase Auth
    // is designed and tested around Fetch; XHR remains a compatibility fallback.
    response = await capturedFetch(input as RequestInfo | URL, init);
  } catch (error) {
    console.warn('[Supabase] fetch failed; retrying once with XHR transport', {
      url,
      error,
    });
    response = await xhrFetch(input, init);
  }

  try {
    const isSupabaseRest = url.includes('/rest/v1/');
    if (isSupabaseRest && response.ok) {
      confirmedAuthFailureCount = 0;
    }
    if (response.status === 401 && isSupabaseRest) {
      const now = Date.now();
      if (now - last401At > 5_000) {
        last401At = now;
        recoverSupabaseAuthAfter401();
      }
    }
  } catch {
    // Response inspection is best-effort and must not break the request.
  }
  return response;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: guardedFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});

supabaseClientRef = supabase;
